#------------------------------------------------------------------------------#
#   /$$$$$$  /$$                               /$$   /$$     /$$               #
#  /$$__  $$| $$                              |__/  | $$    | $$               #
# | $$  \ $$| $$  /$$$$$$   /$$$$$$$  /$$$$$$  /$$ /$$$$$$ /$$$$$$   /$$   /$$ #
# | $$$$$$$$| $$ |____  $$ /$$_____/ /$$__  $$| $$|_  $$_/|_  $$_/  | $$  | $$ #
# | $$__  $$| $$  /$$$$$$$| $$      | $$  \__/| $$  | $$    | $$    | $$  | $$ #
# | $$  | $$| $$ /$$__  $$| $$      | $$      | $$  | $$ /$$| $$ /$$| $$  | $$ #
# | $$  | $$| $$|  $$$$$$$|  $$$$$$$| $$      | $$  |  $$$$/|  $$$$/|  $$$$$$$ #
# |__/  |__/|__/ \_______/ \_______/|__/      |__/   \___/   \___/   \____  $$ #
#                                                                    /$$  | $$ #
#                                                                   |  $$$$$$/ #
#                                                                    \______/  #
#------------------------------------------------------------------------------#

window:
    padding:
        x: 30
        y: 20

font:
    normal:
        family: Iosevka Term
        style: Medium
    bold:
        family: Iosevka Term
        style: Regular
    italic:
        family: Ioevka Term
        style: Regular
    bold_italic:
        family: FiraCode Nerd Font
        style: Bold Italic
    size: 15

    offset:
        x: 0
        y: 0

# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

class:
    instance: Alacritty
    general: Alacritty

bell:
    duration: 0
    command: None

mouse:
    hints:
        launche: None
