#!/bin/zsh

# polybar
polybar main &

# background
feh --bg-fill ~/.background/houses.jpg

# desktop lists
bspc monitor -d code terminal firefox music

# ignore rofi borders
bspc rule -a rofi borders=off

# window borders
bspc config focused_border_color "#668a90"
bspc config normal_border_color "#9d76fb"

# window gaps
bspc config window_gap 20

# desktop padding
bspc config top_padding 50
bspc config bottom_padding 10
bspc config right_padding 10
bspc config left_padding 10

# sxhkd
sxhkd &
