#!/bin/sh

#--------------------------------------------------------------#
#    /$$$$$$$   /$$$$$$  /$$$$$$$  /$$      /$$ /$$      /$$   #
#   | $$__  $$ /$$__  $$| $$__  $$| $$  /$ | $$| $$$    /$$$   #
#   | $$  \ $$| $$  \__/| $$  \ $$| $$ /$$$| $$| $$$$  /$$$$   #
#   | $$$$$$$ |  $$$$$$ | $$$$$$$/| $$/$$ $$ $$| $$ $$/$$ $$   #
#   | $$__  $$ \____  $$| $$____/ | $$$$_  $$$$| $$  $$$| $$   #
#   | $$  \ $$ /$$  \ $$| $$      | $$$/ \  $$$| $$\  $ | $$   #
#   | $$$$$$$/|  $$$$$$/| $$      | $$/   \  $$| $$ \/  | $$   #
#   |_______/  \______/ |__/      |__/     \__/|__/     |__/   #
#--------------------------------------------------------------#

#-----------------#
# -- VARIABLES -- #
#-----------------#

# colors
BORDER_FOCUSED_COLOR="#cc241d"
BORDER_NORMAL_COLOR="#7c6f64"

# gap size
WINDOW_GAP_SIZE=15

# border size
WINDOW_BORDER_WIDTH=3

# desktop padding
DESKTOP_PADDING_TOP=50
DESKTOP_PADDING_BOTTOM=30
DESKTOP_PADDING_LEFT=30
DESKTOP_PADDING_RIGHT=30

# automatic scheme
DESKTOP_AUTOMATIC_SCHEME="longest_side"

#--------------#
# -- GENERAL --#
#--------------#

bspc config automatic_scheme "${DESKTOP_AUTOMATIC_SCHEME}"

#---------------#
# -- BORDERS -- #
#---------------#

bspc config focused_border_color "${BORDER_FOCUSED_COLOR}"
bspc config normal_border_color  "${BORDER_NORMAL_COLOR}"

#---------------#
# -- WINDOWS -- #
#---------------#

bspc config window_gap   $WINDOW_GAP_SIZE
bspc config border_width $WINDOW_BORDER_WIDTH

#---------------#
# -- DESKTOP -- #
#---------------#

# paddings
bspc config top_padding    $DESKTOP_PADDING_TOP
bspc config bottom_padding $DESKTOP_PADDING_BOTTOM
bspc config right_padding  $DESKTOP_PADDING_RIGHT
bspc config left_padding   $DESKTOP_PADDING_LEFT

# create desktops
bspc monitor -d "browser" "code" "terminal" "files" "music" "downloads"

#-------------#
# -- RULES -- #
#-------------#

bspc rule -a nemo desktop='files' follow=on focus=on
bspc rule -a transmission-gtk desktop='downloads' follow=on focus=on
bspc rule -a firefox desktop='browser' follow=on focus=on
bspc rule -a nvim desktop='code' follow=on focus=on
bspc rule -a Alacritty desktop='terminal' follow=on focus=on
bspc rule -a ncmpcpp desktop="music" follow=on focus=on
bspc rule -a easytag desktop="music" follow=on focus=on

#-----------------#
# -- AUTOSTART -- #
#-----------------#

# start apps
xsetroot -cursor_name left_ptr
mpd &
polybar &
picom --vsync-use-glfinish &
sxhkd &
polybar --config=~/.config/polybar/config.ini top &
feh --bg-scale ~/.wallpaper/wall.jpg &
