add_newline = true

format = """
$git_branch
$character
"""

[git_branch]
format = "\\[ [$symbol$branch]($style) \\]"
style = "fg:red"
symbol = ""

[character]
format = "$symbol"
success_symbol = "[](fg:green)"
error_symbol = "[][fg:red bold]"

[directory]
truncation_length = 5
truncate_to_repo = true
format = "[$path]($style)"
style = "fg:blue"
home_symbol = "~"
