#!/bin/zsh

#—————————————————————
#—— LOCAL VARIABLES ——
#——————————————————————

# playlist name containing all music
playlist_name="All"

# mpc binary
MPC=($(which mpc) -q)

#—————————————————————————
#—— UPDATE MPD DATABASE ——
#—————————————————————————
music_update () {
	local IFS='$\n'

	if [[ $(mpc lsplaylist | grep "$playlist_name") == "$playlist_name" ]]
	then
		$MPC -q rm "$playlist_name"
	fi

	$MPC --wait update

	$MPC listall |
	while IFS='$\n' read -r artist
	do
		$MPC add "$artist"
	done
	$MPC save "$playlist_name"
}

#————————————————
#—— PLAY MUSIC ——
#————————————————
music_play () {
	if [[ $(mpc | wc -l) == 1 ]]
    then
    	$MPC random on
    	$MPC repeat on
    	$MPC load "$playlist_name"
    	$MPC play
	else
		$MPC toggle
	fi
}

#—————————————————
#—— PAUSE MUSIC ——
#—————————————————
music_pause () {
    $MPC pause
}

#———————————————
#—— SONG GOTO ——
#———————————————
music_go_to() {
	case "$1" in
		"next")
			$MPC next
			;;
		"prev")
			$MPC prev
			;;
	esac
}

#—————————————————————
#—— PARSE ARGUMENTS ——
#—————————————————————
if [[ "$1" == "play" ]]
then
    music_play
elif [[ "$1" == "stop" ]]
then
    music_stop
elif [[ "$1" == "pause" ]]
then
    music_pause
elif [[ "$1" == "update" ]]
then
    music_update
elif [[ "$1" == "goto" ]]
then
	music_go_to $2
fi

#—————————————————————
#—— UNSET FUNCTIONS ——
#—————————————————————
unset playlist_name
unset music_pause
unset music_play
unset music_update
unset music_stop
unset music_go_to