#!/bin/zsh

#————————————————————
#—— REMOVE PACKAGE ——
#————————————————————
remove () {
	yes O | yay  -Rnus $@
}

#—————————————————————————
#—— UPDATE WHOLE SYSTEM ——
#—————————————————————————
update () {
	yes O | yay --answerdiff N --answerupgrade A --answerclean A --answeredit N --cleanafter --devel -Syu
}

#—————————————
#—— INSTALL ——
#—————————————
install () {
	yay --removemake --cleanafter --answerdiff N --answerupgrade A --answerclean A --answeredit N -Sy $1
}

#—————————————————————————
#—— CLEAN WHOLE SYSTEM ——
#—————————————————————————
clean () {
	yes O | yay -Scc

	OUTPUT=$(yay -Qtdq | tr '\n' ' ')
	PKGS=$(echo $OUTPUT | sed "s/[^a-zA-Z]$//gm")

	echo $PKGS

	if [[ ! -z "$OUTPUT" ]]
	then
		remove $PKGS
	fi
}

case "$1" in
	"clean")
		clean
		;;
	"update")
		update
		;;
	"remove")
		remove $2
		;;
	"install")
		install $2
		;;
	*)
		echo -n "\"$1\" option not recognized!"
esac

unset clean
unset update
unset remove
unset clean
